tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('', views.home, name='home'),
    path('undo/<int:id>/', views.undotask, name='undo'),
    path('previous-tasks/<str:batch>/', views.batch_details, name = 'batch-details'),
    path('delete/<int:id>/', views.delete_task, name='delete-task'),

]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    address = models.CharField(max_length= 256, blank = True)

class Batch(models.Model):
    batch = models.DateField(auto_now_add= True)

    class Meta:
        ordering = ['-batch']
        verbose_name = 'Batch'
        verbose_name_plural = 'Batches'

    def __str__(self):
        return self.batch.strftime("%B %d, %Y %A")


class Task(models.Model):
    title = models.CharField(
            max_length = 256,
            blank = False,
            null = False,
        )

    complete = models.BooleanField(
            default= False,
        )
    created = models.DateTimeField(auto_now_add= True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='author')

    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

forms/tasks.py
from django import forms
from django.forms import ModelForm
from tasks.models import *


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title',]

tasks/views.py
from django.shortcuts import render, redirect
from .models import Task, Batch
from forms import tasks
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import datetime
from django.utils.formats import date_format


@login_required
def home(request):
    batch = Batch.objects.filter(batch = datetime.date.today()).first()
    if request.method == 'POST':
        form = tasks.TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            if not batch:
               batch =  Batch.objects.create(batch = datetime.date.today())
            task.author = request.user
            task.batch = batch
            task.save()
        return redirect('tasks:home')
    else:
        form = tasks.TaskForm()
    context = {
        'form' : form,
        'batch_list' : Batch.objects.filter(batch__lt = datetime.date.today()),
        'completed_tasks' : Task.objects.filter(author = request.user,batch__batch = datetime.date.today(), complete = True).order_by('-created'),
        'unfinished_tasks' : Task.objects.filter(author = request.user,batch__batch = datetime.date.today(), complete = False).order_by('-created'),
    }
    return render(request, 'tasks/home.html', context)


def undotask(request, id):
    task = Task.objects.get(id = id)
    if request.method  == 'POST':
        if task.complete == True:
            task.complete = False
        else:
            task.complete = True
        task.save()
    return redirect('tasks:home')


def batch_details(request, batch):
    task_list = Task.objects.filter(author = request.user, batch__batch = batch).order_by('-created')
    batch_list = Batch.objects.filter(batch__lt = datetime.date.today())
    context = {
        'task_list' : task_list,
        'batch_list' : batch_list,
        'specific_batch': Batch.objects.get(batch = batch),
    }
    return render(request, 'tasks/batch_details.html', context)

def delete_task(request, id):
    delete_task = Task.objects.get(id = id)
    delete_task.delete()
    return redirect('tasks:home')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>ToDO | {% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}

{% block content %}
    <div class="container">
        <form method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input class="btn btn-primary mt-2" type="submit" name="">
    </form>
    </div>

{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
    <h6>you are now logged out. <a href="{% url 'login' %}">Sign in again?</a> </h6>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="width:100%">
  <div class="container">
    <a class="navbar-brand" href="{% url 'tasks:home' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'tasks:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {%  if user.is_superuser %}
              <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Page</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <a href="{% if user.is_authenticated %} {% url 'logout' %} {% else %}{% url 'login' %}{% endif %} " class="btn btn-outline-success">{% if user.is_authenticated %}Logout {% else %} Login {% endif %}</a>
      </form>
    </div>
  </div>
</nav>

templates/tasks/batch_details.html
{% extends 'base.html' %}
{% load app_filters %}


{% block title %}Task{% endblock %}


{% block content %}
<div class="container mt-5">
    user: {{request.user}}
        <div class="mt-4">Tasks from {{specific_batch}} :</div>
    <ul class="list-group">
        {% for task in task_list %}
            <li class="list-group-item mt-1">
                <div class="row">
                    <div class="col-sm">
                        {{ task.title }}
                    </div>
                    <div class="col-sm">
                        <p class="mb-1 " style="float: right;">
                           <small class="text-muted" style="float: right;">
                            {{task.created}} {% if task.complete %}&nbsp &nbsp &nbsp &nbsp &nbsp Done{% else %}&nbsp Unfinished{% endif %}
                        </small>
                        </p>
                    </div>
                </div>
            </li>
        {% endfor %}
        </ul>

    <div class="mt-4">Tasks from previous days:</div>
    <ul class="list-group">
        {% for batch in batch_list %}

        <li class="list-group-item">
            <div class="row">
                <div class="col-sm">
                    {{batch}}
                </div>
                <div class="col-sm">
                    <a href="{% url 'tasks:batch-details' batch.batch %}" class="btn btn-outline-primary btn-sm" style="float: right;">View</a>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>

</div>


{% endblock %}

templates/tasks/home.html
{% extends 'base.html' %}
{% load app_filters %}


{% block title %}Task{% endblock %}


{% block content %}
<div class="container mt-5">
    user: {{request.user}}
        <form method="POST">
            {% csrf_token %}
            {{form.title}}
            <input class="btn btn-outline-primary" type="submit">
        </form>
        <div class="mt-4">Tasks:</div>

        <ul class="list-group">
            {% for task in unfinished_tasks %}
                <li class="list-group-item mt-1">
                    <div class="row">
                        <div class="col-sm">
                            {{ task.title }}
                        </div>
                        <div class="col-sm">
                            <p class="mb-1 " style="float: right;">
                                <form action="{% url 'tasks:undo' task.id %}" method="POST" style="float: right">
                                    {% csrf_token %}
                                    &nbsp<button type="submit" action="#"class="btn btn-outline-success btn-sm">Done</button>
                                    <a href="{% url 'tasks:delete-task' task.id %}" class="btn btn-close"></a>
                                </form>
                                <small class="text-muted" style="float: right;"> {{task.created}} </small>
                            </p>
                        </div>
                    </div>
                </li>
                {% empty %}
                <small class="text-muted">Input some tasks that you need to do.</small>
            {% endfor %}
        </ul>
        <div class="mt-4">Completed task/s:</div>
    <ul class="list-group">
        {% for task in completed_tasks %}
            <li class="list-group-item mt-1">
                <div class="row">
                    <div class="col-sm">
                        {{ task.title }}
                    </div>
                    <div class="col-sm">
                        <div class="col-sm">
                            <form action="{% url 'tasks:undo' task.id %}" method="POST" style="float: right">
                                {% csrf_token %}
                                &nbsp <button type="submit" action="#"class="btn btn-outline-danger btn-sm">Undo</button>
                                <a href="{% url 'tasks:delete-task' task.id %}" class="btn btn-close"></a>
                            </form>
                            <small class="text-muted" style="float: right;"> {{task.created}} </small>
                        </div>
                    </div>
                </div>
            </li>
            {% empty %}
                <small class="text-muted">No task completed yet.</small>
        {% endfor %}
    </ul>

    <div class="mt-4">Tasks from previous days:</div>
    <ul class="list-group">
        {% for batch in batch_list %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col-sm">
                        {{batch}}
                    </div>
                    <div class="col-sm">
                        <a href="{% url 'tasks:batch-details' batch.batch%}" class="btn btn-outline-primary btn-sm" style="float: right;">View</a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>

</div>


{% endblock %}